name: Sport24
description: Web Developer from Somewhere
url: http://36523.github.io
baseurl: ""
permalink: /:title/
sass:
  style: :expanded # You might prefer to minify using :compressed
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
